//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLACIKPOZISYONLAR
    {
        public int POZISYON_REFNO { get; set; }
        public string POZISYON_ADI { get; set; }
        public string POZISYON_DETAYI { get; set; }
        public bool POZISYON_DURUMU { get; set; }
        public System.DateTime TARIH { get; set; }
    }
}
