//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGENELBASVURU
    {
        public int BASVURU_REFNO { get; set; }
        public string BASVURAN_ADI { get; set; }
        public string BASVURAN_SOYADI { get; set; }
        public string BASVURAN_OKUL { get; set; }
        public string BASVURAN_EHLIYET { get; set; }
        public string DOSYA_ADI { get; set; }
    }
}
