//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGELIR_GIDER
    {
        public int GELIR_GIDER_REFNO { get; set; }
        public int GG_TIPI_REFNO { get; set; }
        public bool GELIR_GIDER_TURU { get; set; }
        public decimal BORC { get; set; }
        public decimal ALACAK { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual TBLGG_TIPI TBLGG_TIPI { get; set; }
    }
}
