//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGG_TIPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLGG_TIPI()
        {
            this.TBLGELIR_GIDER = new HashSet<TBLGELIR_GIDER>();
        }
    
        public int GG_TIPI_REFNO { get; set; }
        public string GG_TIPI_ADI { get; set; }
        public bool GG_TURU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLGELIR_GIDER> TBLGELIR_GIDER { get; set; }
        public virtual TBLGG_TIPI TBLGG_TIPI1 { get; set; }
        public virtual TBLGG_TIPI TBLGG_TIPI2 { get; set; }
    }
}
