//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICILAR
    {
        public int KULLANICI_REFNO { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string KULLANICI_SIFRE { get; set; }
        public bool KULLANICI_DURUMU { get; set; }
        public int KULLNICI_TIPI_REFNO { get; set; }
        public string MAIL { get; set; }
    
        public virtual TBLKULLANICITIPLERI TBLKULLANICITIPLERI { get; set; }
    }
}
