//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOGIN
    {
        public int LOGIN_REFNO { get; set; }
        public string LOGIN_FULLNAME { get; set; }
        public string LOGIN_MAIL { get; set; }
        public string LOGIN_TEL { get; set; }
    }
}
