//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUYE_HAREKET
    {
        public int UYE_HAR_REFNO { get; set; }
        public int UYE_PROJE_REFNO { get; set; }
        public decimal BORC { get; set; }
        public decimal ALACAK { get; set; }
        public System.DateTime TARIH { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual TBLUYE_PROJE TBLUYE_PROJE { get; set; }
    }
}
