//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUYE_PROJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYE_PROJE()
        {
            this.TBLUYE_HAREKET = new HashSet<TBLUYE_HAREKET>();
        }
    
        public int UYE_PROJE_REFNO { get; set; }
        public int UYE_REFNO { get; set; }
        public int PROJE_REFNO { get; set; }
        public decimal PESINAT { get; set; }
        public decimal TOPLAM_TUTAR { get; set; }
        public int TAKSIT_SAYISI { get; set; }
        public decimal AYLIK_TUTAR { get; set; }
    
        public virtual TBLPROJELER TBLPROJELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYE_HAREKET> TBLUYE_HAREKET { get; set; }
        public virtual TBLUYELER TBLUYELER { get; set; }
    }
}
