//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSAATTaksitTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYELER()
        {
            this.TBLMESAJLAR = new HashSet<TBLMESAJLAR>();
            this.TBLUYE_PROJE = new HashSet<TBLUYE_PROJE>();
        }
    
        public int UYE_REFNO { get; set; }
        public string UYE_AD { get; set; }
        public string UYE_SOYAD { get; set; }
        public string UYE_ADRES { get; set; }
        public string UYE_TELEFON { get; set; }
        public Nullable<int> SEHIR_REFNO { get; set; }
        public Nullable<int> ILCE_REFNO { get; set; }
        public string UYE_MAIL { get; set; }
        public string PAROLA { get; set; }
    
        public virtual TBLILCELER TBLILCELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMESAJLAR> TBLMESAJLAR { get; set; }
        public virtual TBLSEHIRLER TBLSEHIRLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYE_PROJE> TBLUYE_PROJE { get; set; }
    }
}
